apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: kafka-external-autoscaler
  namespace: myproject
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: consumer1-topic0001-group-0001
  minReplicas: 1
  maxReplicas: 10
  # For a full list of metrics supported run:
  #   $ kubectl get --raw "/apis/custom.metrics.k8s.io/v1beta1" | jq -r ".resources[].name"
  metrics:
  - type: External
    external:
      metricName: "kafka.consumer_lag"
      metricSelector:
        matchLabels:
          topic: topic0001
      targetValue: 10
